question_list = [
  ("who was the Ancient Greek God of the Sun?", "Apollo".lower()),
  ("what is acrophobia a fear of?", "Height".lower()),
  ("What city is known as 'The Ethernal City'?", "Rome".lower()),
  ("where is the world's largest waterfall (Angel Falls) located?", "Venezuela".lower()),
  ("what is the capital of Nigeria?", "Abuja".lower()),
  ("what is the capital of Ireland?", "Dublin".lower()),
  ("what country features a shipwreck on its national flag?", "Bermuda".lower()),
  ("which club is the best club in europe after winning the league unbeaten?", "Arsenal".lower()),
  ("who is the most awarded artist in Africa?", "Wizkid".lower()),
  ("which is the only body part that is fully grown from birth?", "Eyes".lower()),
  ("what is the smallest unit of matter?", "Atom".lower()),
  ("what is the process by which a liquid changes into a gas?", "Evaporation".lower()),
  ("what year was the United Nations established?", "1945".lower()),
  ("which country is credited with inventing ice cream?", "China".lower()),
  ("which country has won the most world cups?", "Brazil".lower()),
  ("how many hearts does an octopus have?", "Three".lower()),
  ("what has an eye but cannot see?", "Needle".lower()),
  ("what is always coming but never arrives?", "Tomorrow".lower()),
  ("what has to be broken before you can use it?", "Egg".lower()),
  ("what has a neck but no head?", "Bottle".lower()),
  ("what gets smaller everytime it takes a bath?", "Soap".lower()),
  ("what has a head but no brain?", "Lettuce".lower()),
  ("what comes down but never goes up?", "Rain".lower()),
  ("David's father has three sons: Snap, crackle and ?", "David".lower()),
  ("what is full of holes but still holds water?", "Sponge".lower()),
  ("the more you take, the more you leave behind. What am I?", "Footsteps".lower())
]